"""
Dictionaries to unify nomenclature of primary organs
and metastatic sites across different publications.
"""

cancer_unification_dict = {
 'adrenal': "adrenal",
 'anus': "anus",
 'appendix': "appendix",
 'bile duct': "bile duct",
 'biliary': "bile duct",
 'bladder': "bladder",
 'bone': "bone",
 'branchial cyst': "branchial cyst",
 'breast': "breast",
 'cervical': "cervix",
 'cervix': "cervix",
 'colon': "colon",
 'colorectal': "colorectal",
 'duodenum': "duodenum",
 'esophageal_and_gastric': "esophageal and gastric",
 'esophagus': "esophagus",
 'eye': "eye",
 'gallbladder': "gallbladder",
 'head_and_neck': "head neck",
 'kidney': "kidney",
 'larynx': "larynx",
 'lip': "lip",
 'liver': "liver",
 'lung': "lung",
 'melanoma': "skin",
 'neuroendocrine': "neuroendocrine",
 'ovarian': "ovary",
 'ovary': "ovary",
 'pancreas': "pancreas",
 'pancreatic': "pancreas",
 'penis': "penus",
 'pharynx': "pharynx",
 'pleura': "pleura",
 'prostate': "prostate",
 'rectum': "rectum",
 'retroperitoneum': "retroperitoneum",
 'salivary': "salivary",
 'skin body': "skin body",
 'skin lower face': "skin lower face",
 'skin upper face': "skin upper face",
 'small intestine': "small intestine",
 'stomach': "stomach",
 'testicular': "testis",
 'testis': "testis",
 'thyroid': "thyroid",
 'tongue': "tongue",
 'tonsil': "tonsil",
 'unkown primary': "unkown primary",
 'urinary_tract': "urinary tract",
 'uterus': "uterus",
 'vagina': "vagina",
 'vulva': "vulva"
}

metastatic_site_unification_dict = {
 'abdom nodes': "abdominal nodes",
 'abdominal LN': "abdominal nodes",
 'adrenal': "adrenal gland",
 'adrenal glands': "adrenal gland",
 'adrenal_gland': "adrenal gland",
 'andomen cav': "abdomen cavity",
 'auxiliary nodes': "axillary nodes",
 'axillary LN': "axillary nodes",
 'bile duct': "bile duct",
 'bladder': "bladder",
 'bone': "bone",
 'bone_marrow': "bone marrow",
 'brain': "brain",
 'brain cerebral': "brain",
 'brain dural': "drop",
 'breast': "breast",
 'cervical nodes': "cervical nodes",
 'cervix': "cervix",
 'diaphragm': "diaphragm",
 'esophagus': "esophagus",
 'fallopian tubes': "fallopian tubes",
 'gallbladder': "gallbladder",
 'gastroint tract': "gastrointestinal tract",
 'heart': "heart",
 'inguinal nodes': "inguinal nodes",
 'intestinal LN': "intestinal nodes",
 'kidney': "kidney",
 'large intestine': "large intestine",
 'limph nodes dist': "distant lymph nodes",
 'limph nodes reg': "regional lymph nodes",
 'liver': "liver",
 'lung': "lung",
 'mediast nodes': "mediastinal nodes",
 'mediastinal LN': "mediastinal nodes",
 'meninges': "meninges",
 'mesentery': "mesentery",
 'non_regional_lymph_nodes': "distant lymph nodes",
 'omentum': "omentum",
 'other': "other",
 'other_site': "other",
 'ovaries': "ovary",
 'ovary': "ovary",
 'pancreas': "pancreas",
 'parotid gland': "parotid gland",
 'pelvic LN': "pelvic lymph nodes",
 'pericardium': "pericardium",
 'peritoneum': "peritoneum",
 'pineal gland': "pineal gland",
 'pituitary': "pituitary",
 'pleura': "pleura",
 'prostate': "prostate",
 'retroperitoneal LN': "retroperitoneal lymph nodes",
 'skeletal muscle': "skeletal muscle",
 'skin': "skin",
 'small intestine': "small intestine",
 'soft_tissue': "soft tissue",
 'spinal cord': "spinal cord",
 'spleen': "spleen",
 'sternoclavicular LN': "sternoclavicular lymph nodes",
 'stomach': "stomach",
 'stomach_bowel': "stomach bowel",
 'testes': "testes",
 'thoracic LN': "thoracic lymph nodes",
 'thyroid': "thyroid",
 'trachea': "trachea",
 'ureter': "ureter",
 'ureter_urethra': "ureter uretra",
 'uterus': "uterus",
 'vagina': "vagina"
}